### ISSUE TITLE
All hosted maps have been silently corrupted.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA-Resources#266]
https://github.com/OpenRA/OpenRA/pull/9324 introduced a map format upgrade (7 &rarr; 8). https://github.com/OpenRA/OpenRA-Resources/pull/262/ (I think) added a feature that does a lint check for all supported game versions, including bleed.

When the bleed linter tested each map it automatically upgraded the underlying file to format 8, which means that the map hash stored in the database no longer matches the hash of the oramap, which broke the ability to install maps ingame.  The format 8 will be parsed by the game, but the color definitions are treated as bogus and ignored.

You can fix this in two ways: Either write some custom code that undoes the format upgrade (port the RGB[A] color definitions back to H,S,L and decrement the map version), or export the yaml stored for the "view yaml" api which appears to have been copied from before the lint tests were run back into the oramap.

**Comment by ihptru** [comment]
I'll be checking what's actually going on later tonight. From what I read, all maps should not have been upgraded. Lint check for all versions runs for map which is being uploaded at the moment OR if I run global upgrade/check which happend when september release published. That means only new maps could be corrupted. Older maps should be OK. I'll check.

**Comment by ihptru** [comment]
quick check of maps shows that maps which were uploaded on November 2 and ealier are in MapFormat 7. So they are good.

**Comment by ihptru** [comment]
Prevented map modification while Lint, using file system permissions (It appeared when map object is declared in OpenRA and if MapFormat change takes place, map is modified automatically (Map.cs)).

Affected maps IDs: from  6361  to  6416

Notified authors who had E-Mail in their profiles with next text: 
http://dpaste.com/0PRZC0P

Those maps which will not be re-uploaded, can be auto-fixed with next Full Upgrade after next release.
