### ISSUE TITLE
URLError on resource.openra.net

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA-Resources#267]
From Openra/Openra#10202:

>I can see a map like http://resource.openra.net/maps/1801 and it works.
>If a map doesn't exist like http://resource.openra.net/maps/99999999, I get back to the index.
>If I try to go to http://resource.openra.net/maps/1802, server "crash".
>I don't know if other maps are affected.
>![urlerror](https://cloud.githubusercontent.com/assets/8930382/11757136/3f87746a-a05f-11e5-8846-ee26e1e35a15.png)

**Comment by StexoO** [comment]
The affected maps are http://resource.openra.net/maps/1802, http://resource.openra.net/maps/1816 and http://resource.openra.net/maps/1833.

**Comment by ihptru** [comment]
So fetching HASH using OpenRA.Utility for those maps failed.
Maps are old and can't tell for sure what was the reason.

Record in DB instead of actual hash contains next:
```
Run `OpenRA.Utility.exe [MOD]` to see a list of available commands.The available mods are: cnc, d2k, modchooser, ra, ts
```
Crash is because it tries to talk to master server giving that error I mentioned above as hash argument.

Not only hash was broken, also minimap and everything which was depended on OpenRA.Utility at that moment. I just remove those maps.

**Comment by ihptru** [comment]
Thanks for report
