### ISSUE TITLE
Integrate with new rule update system.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA-Resources#318]
The next playtest will ship with a completely new system for updating map rules, which uses a different utility command name, and the old command is being removed.  The automated and user-prompted upgrade actions here will need to be updated to work with the new code.

**Comment by dsimmons87** [comment]
Just for reference:

https://github.com/OpenRA/OpenRAModSDK/wiki/Updating-to-a-new-SDK-or-Engine-version

Use --update-map instead of --update-mod for maps and there's no explicit confirmation step

**Comment by dsimmons87** [comment]
Ok I've updated it in this PR:

#319 

There was an issue whereby the new updater doesn't just pass or fail. Often it passes and asks for manual changes. Because of this, where manual changes are needed (any "advanced" map), it redirects to a page showing the console output so users can see what needs to be done.

**Comment by pchote** [comment]
Fixed by #319.
